Repository navikt/kviss, pull requests merged in 2022-08, with the labels that each got.

#157 152 set dynamic score for players
  backend/src/main/kotlin/nav/no/ApplicationContext.kt
  backend/src/main/kotlin/nav/no/database/dao/AnswerDao.kt
  backend/src/main/kotlin/nav/no/database/dao/GameDao.kt
  backend/src/main/kotlin/nav/no/database/dao/PlayerDao.kt
  backend/src/main/kotlin/nav/no/models/Quiz.kt
  backend/src/main/kotlin/nav/no/routes/GameRoute.kt
  backend/src/main/kotlin/nav/no/services/GameService.kt
  backend/src/main/kotlin/nav/no/sockets/EventHandler.kt
  backend/src/main/kotlin/nav/no/sockets/IncomingEvents.kt
  backend/src/main/kotlin/nav/no/sockets/OutgoingEvents.kt
  backend/src/main/resources/db/migration/V1__init_db.sql
  web/app/components/AnswerButton.tsx
  web/app/components/AnswerView.tsx
  web/app/components/FinalScoreboard.tsx
  web/app/components/Footer.tsx
  web/app/components/Header.tsx
  web/app/components/Lobby.tsx
  web/app/components/Question.tsx
  web/app/components/Scoreboard.tsx
  web/app/components/WaitingView.tsx
  web/app/components/common/Checkbox.tsx
  web/app/components/common/Input.tsx
  web/app/components/common/Radio.tsx
  web/app/components/common/TextArea.tsx
  web/app/components/common/icons/EditIcon.tsx
  web/app/components/quizAdministration/QuestionsPreview.tsx
  web/app/components/quizAdministration/QuizInformationForm.tsx
  web/app/context/game/GameContext.tsx
  web/app/context/game/game.ts
  web/app/routes/game.tsx
  web/app/routes/game/index.tsx
  web/app/routes/game/lobby/host/index.tsx
  web/app/routes/game/lobby/index.tsx
  web/app/routes/index.tsx
  web/app/routes/join/index.tsx
  web/app/routes/start/index.tsx
  web/server/src/api.ts
  web/server/src/event-handler.ts
  web/server/src/events/incoming.ts
  web/server/src/events/outgoing.ts
Labels: frontend, chore, feature, backend

#172 Added error message for pin and username
  web/app/routes/join/index.tsx
Labels: frontend, feature

#178 177 is joinable on game
  backend/src/main/kotlin/nav/no/database/dao/GameDao.kt
  backend/src/main/kotlin/nav/no/database/domain/Quiz.kt
  backend/src/main/kotlin/nav/no/models/Quiz.kt
  backend/src/main/kotlin/nav/no/routes/GameRoute.kt
  backend/src/main/kotlin/nav/no/services/GameService.kt
  backend/src/main/resources/db/migration/V2__add_can_join.sql
  backend/src/test/kotlin/nav/no/services/GameServiceTest.kt
  web/server/src/api.ts
Labels: feature, backend

#190 added back button
  web/app/components/FinalScoreboard.tsx
  web/app/routes/game/index.tsx
  web/app/routes/join/index.tsx
Labels: frontend, feature

#200 PlayerLeftEvent methods implemented
  web/app/components/AnswerView.tsx
  web/app/context/game/GameContext.tsx
  web/app/context/game/game.ts
  web/app/routes/game.tsx
  web/app/routes/game/lobby/host/index.tsx
  web/server/src/event-handler.ts
  web/server/src/events/outgoing.ts
Labels: frontend, feature
